import type { Config } from 'tailwindcss';

export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'media',
  theme: {
    extend: {
      colors: {
        // Legacy colors (keep for compatibility)
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        mintGreen: '#CAF187',
        sageGreen: '#B2D675',
        softMint: '#CAF186',
        forestGreen: '#182D1F',
        filtersGray: '#4A4A4A',
        backgroundGray: '#F7F7F5',
        customGray: '#787E8A',
        customGreen: '#99EE9F',
        customYellow: '#FFED5F',
        customRed: '#CC3434',
        customWhite: '#F8F8F8',
        borderGray: '#E0E0E0',
        borderGray2: '#e5e7eb',
        customBlue: '#0518F5',
        mossGreen: '#55655B',

        // Evergrid tokens
        bg: 'rgb(var(--c-bg) / <alpha-value>)',
        surface: 'rgb(var(--c-surface) / <alpha-value>)',
        'surface-alt': 'rgb(var(--c-surface-alt) / <alpha-value>)',
        'surface-strong': 'rgb(var(--c-surface-strong) / <alpha-value>)',
        text: 'rgb(var(--c-text) / <alpha-value>)',
        'text-muted': 'rgb(var(--c-text-muted) / <alpha-value>)',
        'text-faint': 'rgb(var(--c-text-faint) / <alpha-value>)',
        border: 'rgb(var(--c-border) / <alpha-value>)',
        divider: 'rgb(var(--c-divider) / <alpha-value>)',
        primary: 'rgb(var(--c-primary) / <alpha-value>)',
        'primary-hover': 'rgb(var(--c-primary-hover) / <alpha-value>)',
        'primary-soft': 'rgb(var(--c-primary-soft) / <alpha-value>)',
        secondary: 'rgb(var(--c-secondary) / <alpha-value>)',
        'secondary-soft': 'rgb(var(--c-secondary-soft) / <alpha-value>)',
        accent: 'rgb(var(--c-accent) / <alpha-value>)',
        'accent-soft': 'rgb(var(--c-accent-soft) / <alpha-value>)',
        success: 'rgb(var(--c-success) / <alpha-value>)',
        warning: 'rgb(var(--c-warning) / <alpha-value>)',
        danger: 'rgb(var(--c-danger) / <alpha-value>)',
        info: 'rgb(var(--c-info) / <alpha-value>)',
      },
      fontFamily: {
        aeonik: 'var(--font-aeonik)',
        neueMontreal: 'var(--font-neue-montreal)',
        display: 'General Sans, Inter, ui-sans-serif, system-ui, sans-serif',
        mono: 'JetBrains Mono, ui-monospace, monospace',
      },
      borderRadius: {
        sm: '6px',
        md: '10px',
        lg: '14px',
        xl: '20px',
        pill: '999px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(18,32,24,0.06)',
        md: '0 8px 24px rgba(18,32,24,0.08)',
        lg: '0 20px 50px rgba(18,32,24,0.12)',
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
      },
    },
  },
  plugins: [],
} satisfies Config;
